update eslint

diff --git a/.github/workflows/eslint.yml b/.github/workflows/eslint.yml
--- a/.github/workflows/eslint.yml
+++ b/.github/workflows/eslint.yml
@@ -20,6 +20,23 @@ jobs:
       - name: Debug ESLint Report
         run: cat eslint-report.json
 
+      - name: Fail Workflow on ESLint Errors
+        if: always()
+        run: |
+          if [ ! -s eslint-report.json ]; then
+            echo "::error::eslint-report.json is empty. ESLint may have failed to run correctly."
+            exit 1
+          fi
+
+          ERROR_COUNT=$(jq '[.[] | select(.severity == 2)] | length' < eslint-report.json)
+          echo "::error::Found $ERROR_COUNT ESLint errors. Blocking PR merge."
+
+          if [ "$ERROR_COUNT" -gt 0 ]; then
+            exit 1
+          else
+            echo "No ESLint errors found. Workflow passed."
+          fi
+
       - name: ReviewDog - Report ESLint Suggestions
         uses: reviewdog/action-eslint@v1
         with:
@@ -40,23 +57,6 @@ jobs:
       #     else
       #       echo "No ESLint errors found. Workflow passed."
       #     fi
-
-      - name: Fail Workflow on ESLint Errors
-        if: always()
-        run: |
-          if [ ! -s eslint-report.json ]; then
-            echo "::error::eslint-report.json is empty. ESLint may have failed to run correctly."
-            exit 1
-          fi
-
-          ERROR_COUNT=$(jq '[.[] | select(.severity == 2)] | length' < eslint-report.json)
-          echo "::error::Found $ERROR_COUNT ESLint errors. Blocking PR merge."
-
-          if [ "$ERROR_COUNT" -gt 0 ]; then
-            exit 1
-          else
-            echo "No ESLint errors found. Workflow passed."
-          fi
 
   block_merge:
     runs-on: ubuntu-latest
